### ISSUE TITLE
Add Dockerfile to setup repo and submodules

### ISSUE THREAD

**Issue by englehardt** [mozilla/openwpm-crawler#1]
We should include a Dockerfile that sets up the OpenWPM submodule and runs the setup tasks.

**Comment by motin** [comment]
I believe this one can be closed as won't fix in relation to this repo? The OpenWPM repo now has Dockerfile which runs the setup tasks, and that Dockerfile and image is used by this repo.

**Comment by englehardt** [comment]
I agree
