### ISSUE TITLE
Do failed sites get re-run?

### ISSUE THREAD

**Issue by birdsarah** [mozilla/openwpm-crawler#12]
Just learning about new redis controller. Wondering if failed sites can be set to retry n times?

**Comment by englehardt** [comment]
They do not, but they definitely should. See: https://github.com/mozilla/OpenWPM/issues/413#issuecomment-513527681

**Comment by motin** [comment]
Closing since the question is answered :)
Created issue to track the feature: https://github.com/mozilla/OpenWPM/issues/422
