### ISSUE TITLE
Add list consumption helper function

### ISSUE THREAD

**Issue by englehardt** [mozilla/openwpm-crawler#2]
We want to deploy crawls on a cluster of machines. Each machine should be able to pull a job list from a specific location and mark the job as in progress and then complete.

Here's a past example of this: https://github.com/jasonthomas/OpenWPM/commit/163d9fd58a9da9a8f597dd47219512e079172c9b

**Comment by motin** [comment]
This work was completed in https://github.com/mozilla/openwpm-crawler/pull/7 using a Redis-based work queue
